apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: kcp
  namespace: ralphjbean
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: kcp
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: kcp
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: kcp-
      labels:
        build.appstudio.openshift.io/application: kcp
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: kcp
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: ralphjbean
    spec:
      params:
      - name: git-url
        value: https://github.com/kcp-dev/kcp
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:ralphjbean-kcp-$(tt.params.git-revision)
      - name: dockerfile
        value: Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:latest
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: kcp/$(tt.params.git-revision)
    status: {}
status: {}
